services:

  wireguard:
    image: denisix/wireguard
    devices:
      - /sys/class/net/wg0
    environment:
      - NAT=1
      - INTERFACE=eth0
      - PORT=10000
      - PUBLIC_IP=1.2.3.4
      - DNS=8.8.8.8,8.8.4.4
      - SUBNET_IP=10.88.0.1/16
      - CLIENTCONTROL_NO_LOGS=0
      - WG_CLIENTS_UNSAFE_PERMISSIONS=0
    volumes:
      - ./wireguard/:/etc/wireguard/
    ports:
      - 10000:10000/udp
    cap_add:
      - SYS_MODULE
      - NET_ADMIN
    sysctl:
      - "net.ipv4.conf.all.src_valid_mark=1"
    privileged: true
    restart: unless-stopped
